import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {CloudHTTP,remoteId} from '../skills/offload/scripts/lib/http.mjs';
import {CursorAdapter,DevinAdapter,ClaudeAdapter,cursorPayload,devinPayload} from '../skills/offload/scripts/lib/providers.mjs';
import {Store} from '../skills/offload/scripts/lib/store.mjs';
import {Core} from '../skills/offload/scripts/lib/core.mjs';
import {newBinding,saveConfig} from '../skills/offload/scripts/lib/config.mjs';
import {cursorEnvironment} from '../skills/offload/scripts/lib/plan.mjs';
import {sample,recipeSample,temp,jsonResponse,repoFixture,gitNetworkShim} from './helpers.mjs';
const jobId='ofl_22222222-2222-2222-2222-222222222222';
const job={id:jobId,repository:'example/fixture',recipeHash:'a'.repeat(64),planHash:'b'.repeat(64),snapshot:{commit:'c'.repeat(40),ref:'refs/heads/offload/'+jobId}};
function binding(provider){return{...newBinding(provider,'example/fixture'),accountLabel:'fixture',enabled:true,allowExperimental:true,allowEnvironmentCreate:true,allowSharedEnvironment:true,allowPromptGitGate:true,expectedPrincipal:'person@example.invalid',organizationId:'org-test',createAsUserId:'user-test',credentialEnv:'TEST_TOKEN'};}
function setup(provider,handler){const dir=temp(),s=new Store(dir),calls=[];const fetchFn=async(url,init)=>{calls.push({url,method:init.method,body:init.body?JSON.parse(init.body):null});assert.equal(init.redirect,'error');assert.equal(new URL(url).hostname,provider==='cursor'?'api.cursor.com':'api.devin.ai');return handler(url.replace(/^https:\/\/[^/]+/,''),init,calls);};return{s,dir,calls,options:{fetchFn,env:{TEST_TOKEN:'fixture-only'}},close(){s.close();fs.rmSync(dir,{recursive:true});}};}
test('HTTP 401 definite rejection; raw error/credentials hidden',async()=>{const h=new CloudHTTP('cursor',{credentialEnv:'T'},{env:{T:'secret'},fetchFn:async()=>jsonResponse({token:'secret'},401)});await assert.rejects(()=>h.request('POST','/v1/agents',{}),e=>e.code==='NEEDS_AUTH'&&e.definitelyNotAccepted&&!JSON.stringify(e).includes('secret'));});
for(const status of [408,409,429,500,503])test(`HTTP ${status} is never blindly write-retried`,async()=>{let n=0;const h=new CloudHTTP('cursor',{credentialEnv:'T'},{env:{T:'fixture'},fetchFn:async()=>{n++;return jsonResponse({},status);}});await assert.rejects(()=>h.request('POST','/v1/agents',{}),e=>!e.definitelyNotAccepted);assert.equal(n,1);});
test('HTTP cannot choose arbitrary credential destination',async()=>{const h=new CloudHTTP('cursor',{credentialEnv:'T'},{env:{T:'fixture'},fetchFn:()=>assert.fail()});await assert.rejects(()=>h.request('GET','https://evil.test'),e=>e.code==='UNSAFE_ENDPOINT');});
test('HTTP follows complete pagination',async()=>{let n=0;const h=new CloudHTTP('cursor',{credentialEnv:'T'},{env:{T:'fixture'},fetchFn:async()=>jsonResponse(++n===1?{items:[1],nextCursor:'p2'}:{items:[2]})});assert.deepEqual(await h.pages('/v1/environments'),[1,2]);});
test('HTTP stops repeated cursor rather than inferring absence',async()=>{const h=new CloudHTTP('cursor',{credentialEnv:'T'},{env:{T:'fixture'},fetchFn:async()=>jsonResponse({items:[],nextCursor:'same'})});await assert.rejects(()=>h.pages('/v1/environments'),e=>e.code==='INCOMPLETE_DISCOVERY');});
test('malformed JSON after successful write leaves outcome uncertain',async()=>{const h=new CloudHTTP('cursor',{credentialEnv:'T'},{env:{T:'fixture'},fetchFn:async()=>new Response('not-json',{status:200})});await assert.rejects(()=>h.request('POST','/v1/agents',{}),e=>e.code==='REMOTE_SCHEMA_CHANGED'&&!e.definitelyNotAccepted);});
test('network failure after POST is unknown',async()=>{const h=new CloudHTTP('cursor',{credentialEnv:'T'},{env:{T:'fixture'},fetchFn:async()=>{throw Error('private diagnostic');}});await assert.rejects(()=>h.request('POST','/v1/agents',{}),e=>e.code==='SUBMISSION_UNKNOWN'&&!e.message.includes('private'));});
test('invalid remote identifiers blocked',()=>assert.throws(()=>remoteId('../other'),e=>e.code==='REMOTE_SCHEMA_CHANGED'));
test('Cursor payload uses named cloud without mutually exclusive repos',()=>{const p=cursorPayload(job,'plan',binding('cursor'),{name:'dev'});assert.deepEqual(p.env,{type:'cloud',name:'dev'});assert.equal(p.repos,undefined);assert.equal(p.mode,'agent');assert.equal(p.autoCreatePR,false);assert.equal(p.agentId,'bc-'+jobId.slice(4));});
test('Cursor named environment requires explicit commit-gate approval',()=>{const b=binding('cursor');b.allowPromptGitGate=false;assert.throws(()=>cursorPayload(job,'plan',b,{name:'dev'}),e=>e.code==='NEEDS_APPROVAL');});
test('Devin payload keeps principal and repo, no bypass/inline secrets',()=>{const p=devinPayload(job,'plan',binding('devin'));assert.equal(p.create_as_user_id,'user-test');assert.deepEqual(p.repos,['example/fixture']);assert.equal(p.bypass_approval,undefined);assert.equal(p.session_secrets,undefined);});
function cursorServer(recipe,{buildStatus='SUCCEEDED',created='2026-10-09T00:01:00Z',mismatch=false}={}){
 let exists=false;const e={id:'env-test',name:binding('cursor').environmentName,owner:'personal',repos:[{url:'https://github.com/example/fixture'}],environmentJson:JSON.stringify(cursorEnvironment(recipe)),updatedAt:'2026-10-09T00:00:00Z',versionId:'version-1'};
 return async(endpoint,init)=>{
  if(endpoint==='/v1/me')return jsonResponse({userId:1,userEmail:mismatch?'other@example.invalid':'person@example.invalid'});
  if(endpoint.startsWith('/v1/environments?'))return jsonResponse({items:exists?[e]:[]});
  if(endpoint==='/v1/environments'&&init.method==='POST'){exists=true;return jsonResponse(e,201);}
  if(endpoint==='/v1/environments/env-test')return jsonResponse(e);
  if(endpoint.includes('/builds?'))return jsonResponse({items:[{id:'build-1',environmentId:e.id,createdAt:created,status:buildStatus,draft:false}]});
  throw Error('unexpected endpoint '+endpoint);
 };
}
test('Cursor creates personal environment then verifies matching build',async()=>{const r=recipeSample(),f=setup('cursor',cursorServer(r));try{const a=new CursorAdapter(f.s,binding('cursor'),f.options),env=await a.ensure(job,r);assert.equal(env.state,'LAUNCHABLE');assert.equal(env.buildId,'build-1');assert.equal(f.calls.filter(x=>x.method==='POST').length,1);await a.ensure(job,r);assert.equal(f.calls.filter(x=>x.method==='POST').length,1);}finally{f.close();}});
for(const [name,opts,state] of [['old successful build',{created:'2026-10-08T00:00:00Z'},'ENVIRONMENT_BUILDING'],['failed build',{buildStatus:'FAILED'},'ENVIRONMENT_FAILED'],['running build',{buildStatus:'IN_PROGRESS'},'ENVIRONMENT_BUILDING'],['wrong user',{mismatch:true},'ACCOUNT_MISMATCH']])test(`Cursor rejects ${name}`,async()=>{const r=recipeSample(),f=setup('cursor',cursorServer(r,opts));try{await assert.rejects(()=>new CursorAdapter(f.s,binding('cursor'),f.options).ensure(job,r),e=>e.code===state);}finally{f.close();}});
test('Cursor submit journals exact receipt and avoids duplicate POST',async()=>{const f=setup('cursor',async()=>jsonResponse({agent:{id:'bc-'+jobId.slice(4),env:{type:'cloud',name:'dev'},url:'https://cursor.com/agents/bc-'+jobId.slice(4)},run:{id:'run-test',agentId:'bc-'+jobId.slice(4)}}));try{const a=new CursorAdapter(f.s,binding('cursor'),f.options),env={name:'dev'};const r=await a.submit(job,'plan',env);assert.equal(r.runId,'run-test');assert.equal((await a.submit(job,'plan',env)).id,r.id);assert.equal(f.calls.length,1);}finally{f.close();}});
test('Cursor recovers lost write response by saved client ID, not another POST',async()=>{let lost=true;const f=setup('cursor',async(endpoint,init)=>{if(init.method==='POST'&&lost){lost=false;throw Error('lost response');}return jsonResponse({id:'bc-'+jobId.slice(4),name:'offload:'+jobId,env:{type:'cloud',name:'dev'},latestRunId:'run-test',url:'https://cursor.com/agents/bc-'+jobId.slice(4)});});try{const a=new CursorAdapter(f.s,binding('cursor'),f.options);await assert.rejects(()=>a.submit(job,'plan',{name:'dev'}),e=>e.code==='SUBMISSION_UNKNOWN');const r=await a.submit(job,'plan',{name:'dev'});assert.equal(r.runId,'run-test');assert.equal(f.calls.filter(x=>x.method==='POST').length,1);}finally{f.close();}});
test('Cursor status reads original run instead of confusing agent IDLE with success',async()=>{const f=setup('cursor',async endpoint=>jsonResponse(endpoint==='/v1/me'?{userId:1,userEmail:'person@example.invalid'}:{id:'run-test',agentId:'agent-test',status:'ERROR',result:'failed'}));try{const r=await new CursorAdapter(f.s,binding('cursor'),f.options).status({id:'agent-test',runId:'run-test'});assert.equal(r.remoteState,'ERROR');assert.equal(r.resultVerdict,'UNVERIFIED');}finally{f.close();}});
test('Devin explicitly builds after Blueprint POST and reuses on resume',async()=>{let exists=false;const bp={blueprint_id:'bp-test',repo_name:'example/fixture',updated_at:1};const f=setup('devin',async(endpoint,init)=>{if(endpoint.endsWith('/blueprints')&&init.method==='GET')return jsonResponse({items:exists?[bp]:[]});if(endpoint.endsWith('/blueprints')&&init.method==='POST'){exists=true;return jsonResponse(bp,201);}if(endpoint.endsWith('/builds')&&init.method==='POST')return jsonResponse({build_id:'build-test',status:'pending'},201);if(endpoint.endsWith('/builds/build-test'))return jsonResponse({build_id:'build-test',status:'succeeded'});throw Error(endpoint);});try{const a=new DevinAdapter(f.s,binding('devin'),f.options);await assert.rejects(()=>a.ensure(job,recipeSample()),e=>e.code==='ENVIRONMENT_BUILDING');assert.deepEqual(f.calls.filter(x=>x.method==='POST').map(x=>x.url.split('/').pop()),['blueprints','builds']);assert.equal((await a.ensure(job,recipeSample())).state,'LAUNCHABLE');assert.equal(f.calls.filter(x=>x.method==='POST').length,2);}finally{f.close();}});
test('Devin stops unapproved shared repositories before writes',async()=>{const f=setup('devin',async()=>jsonResponse({items:[{blueprint_id:'bp-other',repo_name:'private/other'}]}));try{await assert.rejects(()=>new DevinAdapter(f.s,binding('devin'),f.options).ensure(job,recipeSample()),e=>e.code==='SHARED_SCOPE_CHANGED');assert.equal(f.calls.filter(x=>x.method==='POST').length,0);}finally{f.close();}});
test('Devin refuses silently overwriting existing blueprints',async()=>{const f=setup('devin',async()=>jsonResponse({items:[{blueprint_id:'bp-existing',repo_name:'example/fixture'}]}));try{await assert.rejects(()=>new DevinAdapter(f.s,binding('devin'),f.options).ensure(job,recipeSample()),e=>e.code==='ENVIRONMENT_REVIEW_REQUIRED');}finally{f.close();}});
test('Devin wrong returned principal is not accepted',async()=>{const f=setup('devin',async()=>jsonResponse({session_id:'s-test',org_id:'org-test',user_id:'other',url:'https://app.devin.ai/sessions/s-test'}));try{await assert.rejects(()=>new DevinAdapter(f.s,binding('devin'),f.options).submit(job,'plan'),e=>e.code==='ACCOUNT_MISMATCH');assert.equal(f.s.operation(jobId+':task').state,'STARTED');}finally{f.close();}});
test('Claude uses managed flags, shallow snapshot cwd, and does not inherit API credentials',async()=>{const f=repoFixture(),restore=gitNetworkShim(f),c=new Core(path.join(f.base,'state'));try{
 const b=binding('claude');Object.assign(b,{cliPath:process.execPath,claudeCloudVerified:true,allowSnapshotBundle:true,allowSnapshotPush:true,environmentId:'env-test'});saveConfig(c.store.root,{version:1,defaults:{},bindings:[b]});
 const r=await c.prepare({plan:sample(),repo:f.repo,target:'claude'}),j=c.store.get(r.id),m=c.store.read(r.id,'manifest.json');
 const {publishSnapshot}=await import('../skills/offload/scripts/lib/git.mjs');j.snapshot=publishSnapshot(c.store,j,m,b);c.store.save(j);
 const old=process.env.ANTHROPIC_API_KEY;process.env.ANTHROPIC_API_KEY='should-not-be-forwarded';
 const runner=(binary,args,o)=>{if(args[0]==='--version')return'2.1.224 (Claude Code)';if(args[0]==='auth')return JSON.stringify({loggedIn:true,email:b.expectedPrincipal,authMethod:'oauth'});assert.ok(args.includes('--environment'));assert.ok(!args.includes('--cloud'));assert.ok(args.includes('--bare'));assert.notEqual(o.cwd,f.repo);assert.equal(o.env.ANTHROPIC_API_KEY,undefined);return JSON.stringify({session_id:'session-test',url:'https://claude.ai/code/session-test'});};
 try{const a=new ClaudeAdapter(c.store,b,{runFn:runner});assert.equal((await a.ensure(j)).state,'LAUNCHABLE');assert.equal((await a.submit(j,'plan')).id,'session-test');}finally{if(old===undefined)delete process.env.ANTHROPIC_API_KEY;else process.env.ANTHROPIC_API_KEY=old;}
 }finally{c.close();restore();f.cleanup();}});
test('new Codex UI workflow records intent before writes and forbids repeated clicks',async()=>{const f=repoFixture(),restore=gitNetworkShim(f),c=new Core(path.join(f.base,'state'));try{
 const b=binding('codex');b.allowSnapshotPush=true;saveConfig(c.store.root,{version:1,defaults:{},bindings:[b]});const r=await c.prepare({plan:sample(),repo:f.repo,target:'codex'});c.approve(r.id,c.review(r.id).approvalHash);
 assert.equal((await c.submit(r.id)).state,'NEEDS_UI_DRIVER');const env=await c.uiBegin(r.id,'environment');assert.equal(env.reconcileOnly,false);assert.equal((await c.uiBegin(r.id,'environment')).reconcileOnly,true);
 const proof={nonce:env.nonce,account:'fixture',repository:'example/fixture',flavor:'codex_new_ui',recipeHash:r.recipeHash,evidenceRefs:['host-browser:observed-1'],environmentId:'new-env-test',url:'https://chatgpt.com/c/env-test',personal:true,published:true,validation:'passed'};
 await assert.rejects(()=>c.uiRecord(r.id,'environment',{...proof,nonce:'wrong'}),e=>e.code==='OBSERVATION_MISMATCH');await c.uiRecord(r.id,'environment',proof);
 const task=await c.uiBegin(r.id,'task'),saved=c.store.get(r.id);assert.ok(task.artifactPath.endsWith('dispatch.md'));
 const done=await c.uiRecord(r.id,'task',{...proof,nonce:task.nonce,url:'https://chatgpt.com/c/task-test',taskId:'task-test',commit:saved.snapshot.commit,dispatchHash:saved.dispatchHash,accepted:true});assert.equal(done.state,'SUBMITTED');assert.equal((await c.submit(r.id)).receipt.id,'task-test');
 }finally{c.close();restore();f.cleanup();}});
