#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath } from 'node:url';
import { createInterface } from 'node:readline/promises';
import { Core } from './lib/core.mjs';
import { codexOnboarding } from './lib/codex-onboarding.mjs';
import { capture, inspectRecipe } from './lib/git.mjs';
import { newBinding, saveConfig, providers, parseOffload } from './lib/config.mjs';
import { validatePlan, validateRecipe } from './lib/plan.mjs';
import { stateRoot, readJson, requireThat, fail, executable, privateDir, noSymlink, writePrivate } from './lib/safety.mjs';

export const skillRoot = fileURLToPath(new URL('..', import.meta.url));
const optionNames=new Set(['plan','recipe','repo','host','target','request-id','preview','evidence','scope']);
export function parseCLI(args){
  const result={command:args.shift()||'help',positionals:[],options:{}};
  while(args.length){const t=args.shift();if(!t.startsWith('--')){result.positionals.push(t);continue;}
    const name=t.slice(2);requireThat(optionNames.has(name),'INVALID_OPTION','Unknown option; --local and unattended approval are not supported.');
    requireThat(!(name in result.options),'INVALID_OPTION','Duplicate option.');
    if(name==='preview'){result.options[name]=true;continue;}
    requireThat(args.length&&!args[0].startsWith('--'),'INVALID_OPTION',`Missing value for ${t}.`);result.options[name]=args.shift();
  }
  return result;
}
const help={name:'offload',version:'0.1.2',node:'>=26.0.0 <27.0.0',commands:[
 'inspect --repo PATH',
 'validate --plan FILE [--recipe FILE]',
 'prepare --plan FILE --repo PATH --host pi|opencode|codex|claude|cursor [--target codex|claude|cursor|devin] [--recipe FILE] [--preview] [--request-id ID]',
 'setup codex|claude|cursor|devin --repo PATH',
 'review JOB_ID', 'trust JOB_ID (human terminal only)',
 'submit JOB_ID', 'resume JOB_ID', 'status [JOB_ID]',
 'ui-begin JOB_ID environment|task', 'ui-record JOB_ID environment|task --evidence FILE',
 'install-host pi|opencode [--scope project|global] [--repo PATH]', 'doctor',
],notes:['Plan is generated by the current agent, not by this CLI.','Cloud-only. New Codex setup uses ChatGPT Cloud Environment Onboarding: Setup; request login when needed. No legacy fallback.','API adapters require explicit opt-in until live E2E verification.','skills/offload is self-contained; no npm installation is needed to run this script.']};
function exact(n,p){requireThat(p.length===n,'INVALID_COMMAND','Unexpected or missing positional arguments.');}
function allowed(options,names){requireThat(Object.keys(options).every(k=>names.includes(k)),'INVALID_OPTION','Option not valid for this command.');}
async function interactiveSetup(core,b){
  if(!process.stdin.isTTY||!process.stdout.isTTY)return;
  const rl=createInterface({input:process.stdin,output:process.stdout});
  try{
    console.log('Only the named repository and account will be enabled. Cloud usage may incur charges. No token values will be requested.');
    const name=(await rl.question('Account label (blank keeps disabled): ')).trim();if(!name)return;b.accountLabel=name;
    const yes=async q=>(await rl.question(q+' [y/N] ')).trim().toLowerCase()==='y';
    b.allowExperimental=await yes('Enable this beta/contract-tested adapter without claiming live verification?');
    b.allowSnapshotPush=await yes('Permit an isolated reviewed tree to be pushed to offload/<job-id>?');
    b.allowEnvironmentCreate=await yes('Permit creation of a development environment (and possible setup usage)?');
    b.allowPromptGitGate=await yes('Permit agent instructions to enforce the commit/environment gate where no native ref binding exists?');
    if(b.provider==='cursor')b.expectedPrincipal=(await rl.question('Expected Cursor user ID or email (not an API key): ')).trim();
    if(b.provider==='devin'){
      b.organizationId=(await rl.question('Organization ID: ')).trim();b.allowSharedEnvironment=await yes('Approve this repository list and impact on the organization snapshot?');
      b.createAsUserId=(await rl.question('Create as user ID (blank uses credential principal): ')).trim()||undefined;
    }
    if(b.provider==='claude'){
      b.expectedPrincipal=(await rl.question('Expected claude.ai account email (not a token): ')).trim();
      b.cliPath=executable('claude');b.environmentId=(await rl.question('Managed Cloud environment ID (blank uses verified default): ')).trim()||undefined;
      b.claudeCloudVerified=await yes('Have you verified claude.ai login, the intended account, and a provider-managed Cloud environment?');
      b.allowSnapshotBundle=await yes('Allow CLI bundle fallback ONLY for the isolated approved snapshot checkout?');
    }
    // Codex environment discovery/provisioning belongs to ChatGPT's Setup workflow; no manual ID prompt.
    b.enabled=await yes('Save and enable this exact binding? Per-job human approval remains required.');
  }finally{rl.close();}
}
export function installHost(host,{scope='project',repo=process.cwd(),home=os.homedir()}={}){
  requireThat(['pi','opencode'].includes(host)&&['project','global'].includes(scope),'INVALID_HOST','Supported host installers: pi/opencode, project/global.');
  const base=scope==='project'?path.resolve(repo):home;let file,content;
  if(host==='pi'){
    file=scope==='project'?path.join(base,'.pi','extensions','offload.mjs'):path.join(base,'.pi','agent','extensions','offload.mjs');
    const source=new URL('./hosts/pi.mjs',import.meta.url).href;content=`export { default } from ${JSON.stringify(source)};\n`;
  }else{
    file=scope==='project'?path.join(base,'.opencode','commands','offload.md'):path.join(base,'.config','opencode','commands','offload.md');
    content=`---\ndescription: Turn this conversation into a Plan and send it to one cloud\n---\n\nRead the installed skill at ${JSON.stringify(path.join(skillRoot,'SKILL.md'))}. Follow it in THIS conversation. Source host: opencode. User arguments: $ARGUMENTS\nDo not treat a model name as the cloud destination. Do not execute trust or edit trusted permissions on the user's behalf.\n`;
  }
  noSymlink(file);if(fs.existsSync(file)){requireThat(fs.readFileSync(file,'utf8')===content,'INSTALL_CONFLICT','A different host command already exists; it was not overwritten.');return{file,unchanged:true};}
  writePrivate(file,content);return{file,installed:true,reloadRequired:true};
}
export async function main(argv=process.argv.slice(2)){
  const{command,positionals:p,options:o}=parseCLI([...argv]);
  if(command==='help'||command==='--help'){return help;}
  if(command==='parse'){exact(1,p);return parseOffload(p[0]);}
  if(command==='validate'){exact(0,p);allowed(o,['plan','recipe']);requireThat(o.plan,'INVALID_COMMAND','--plan is required.');validatePlan(readJson(o.plan));if(o.recipe)validateRecipe(readJson(o.recipe));return{valid:true};}
  if(command==='inspect'){exact(0,p);allowed(o,['repo']);const m=capture(o.repo||process.cwd());return{repository:m.repository,head:m.head,fingerprint:m.fingerprint,files:m.files.map(({data,...f})=>f),deleted:m.deleted,...inspectRecipe(m)};}
  if(command==='install-host'){exact(1,p);allowed(o,['scope','repo']);return installHost(p[0],o);}
  if(command==='doctor'){
    exact(0,p);allowed(o,[]);return{node:process.versions.node,stateDirectory:stateRoot(),adapters:{codex:'host-browser-required',claude:'official-managed-cli-experimental',cursor:'api-v1-experimental',devin:'api-v3-and-v3beta1-experimental'},liveVerified:false};
  }
  const core=new Core(stateRoot());
  try{
    if(command==='prepare'){
      exact(0,p);allowed(o,['plan','recipe','repo','host','target','request-id','preview']);requireThat(o.plan,'INVALID_COMMAND','--plan is required.');
      return await core.prepare({plan:readJson(o.plan),recipe:o.recipe?readJson(o.recipe):undefined,repo:o.repo,host:o.host,target:o.target,requestId:o['request-id'],preview:!!o.preview});
    }
    if(command==='setup'){
      exact(1,p);allowed(o,['repo']);requireThat(providers.includes(p[0]),'INVALID_TARGET','Unknown cloud.');
      const m=capture(o.repo||process.cwd()),c=core.config();let b=c.bindings.find(x=>x.repository===m.repository&&x.provider===p[0]);
      if(!b){b=newBinding(p[0],m.repository);c.bindings.push(b);}await interactiveSetup(core,b);saveConfig(core.store.root,c);
      return{configPath:path.join(core.store.root,'config.json'),binding:b,enabled:b.enabled,...(b.provider==='codex'?{onboarding:codexOnboarding(m.repository)}:{}),guide:path.join(skillRoot,'references','setup.md'),note:'Configure only non-secret identifiers here; API tokens stay in the configured environment variables. No cloud environment or task was created by setup.'};
    }
    if(command==='review'){exact(1,p);allowed(o,[]);return core.review(p[0]);}
    if(command==='trust'){
      exact(1,p);allowed(o,[]);requireThat(process.stdin.isTTY&&process.stdout.isTTY,'HUMAN_APPROVAL_REQUIRED','Run trust yourself in a real terminal. Agents must not auto-approve.');
      const review=core.review(p[0]);console.log(JSON.stringify(review,null,2));
      const rl=createInterface({input:process.stdin,output:process.stdout});let answer;
      try{answer=await rl.question('Review ALL files, commands, account, cloud, and spend settings above. Type APPROVE to allow this one job: ');}finally{rl.close();}
      requireThat(answer==='APPROVE','APPROVAL_DECLINED','Nothing was approved.');core.approve(p[0],review.approvalHash);return{approved:true,jobId:p[0],hash:review.approvalHash};
    }
    if(['submit','resume'].includes(command)){exact(1,p);allowed(o,[]);return await core.submit(p[0]);}
    if(command==='status'){requireThat(p.length<=1,'INVALID_COMMAND','At most one job ID is allowed.');allowed(o,[]);return await core.status(p[0]);}
    if(command==='ui-begin'){exact(2,p);allowed(o,[]);return await core.uiBegin(p[0],p[1]);}
    if(command==='ui-record'){exact(2,p);allowed(o,['evidence']);requireThat(o.evidence,'INVALID_COMMAND','--evidence is required.');return await core.uiRecord(p[0],p[1],readJson(o.evidence));}
    fail('INVALID_COMMAND','Unknown command; run help.');
  }finally{core.close();}
}
if(process.argv[1]&&fs.existsSync(process.argv[1])&&fs.realpathSync(process.argv[1])===fileURLToPath(import.meta.url)){
  try{const result=await main();console.log(JSON.stringify(result,null,2));if(result?.error)process.exitCode=2;}
  catch(e){console.error(JSON.stringify({error:{code:e.code||'INTERNAL_ERROR',message:e.code?e.message:'Unexpected error; raw details were not logged.',...(e.code&&e.details?{details:e.details}:{})}}));process.exitCode=2;}
}
